### ISSUE TITLE
Mutation and aging?

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#10]
[(Rodríguez et al., 2017)](https://www.dropbox.com/s/xeou3pm8ynkn1kj/Rodr%C3%ADguez%20et%20al.%20-%202017%20-%20Antagonistic%20pleiotropy%20and%20mutation%20accumulation%20.pdf?dl=0)에서는 뮤테이션의 누적과 aging의 관계를 살펴봅니다.

- [x]  논문읽고, 발표하기
- [x] 좀더 깊이있게 공부하기, 추가 문헌조사?
- [ ] 데이터를 통해 볼 수 있는 노화에 대한 가설 만들기

**Comment by sugyun** [comment]
1. 노화에 따른 mutation은 번식능력의 극대화를 위한 자연선택의 부산물이다.
ex) 젊었을 때 걸릴 수 있는 질병을 예방하지만 늙었을 때는 더 치명적인 질병을 유발하는 유전자(antagonistic pleotropic)가 번식을 위해 자연선택됨.
2. 자연선택의 부산물이라해도 자연선택의 손길이 미치게 됨으로써 특정 패턴을 가지게 된다.

**Comment by sugyun** [comment]
식이제한 시의 수명 연장도 똑같은 맥락으로 설명가능한데, 개체도 유지하기 힘든 상황에서 자손을 낳아서 같이 죽는 것보단 상황이 나아질 때까지 수명을 연장하며 기다린다는 전략으로 이해할 수 있다.
