### ISSUE TITLE
Theoretical approaches for aging 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#14]
It is necessary to examine aging in the theoretical aspect.

[Partridge.Barton.-.1993.-.Optimally.mutation.and.the.evolution.of.ageing](https://github.com/jehoons/sbie_aging/files/790564/Partridge.Barton.-.1993.-.Optimally.mutation.and.the.evolution.of.ageing.pdf)

@sugyun, you will be interested in this paper because actually this paper provides the theoretical background of the paper on mutation and aging (#10). 얘네들이 정확히 수동형, 능동형 노화의 컨셉을 이야기한다고 볼 수 있다.

> Organisms might have evolved the optimal life history, in which **survival and fertility late in life are sacrificed for the sake of early reproduction and survival**. Alternatively, the **life history might be depressed below this optimal compromise by deleterious mutations**: because selection against late-acting mutations is weaker, these will impose a greater load on late life. 

> The `disposable soma theory` is an optimality account of ageing, in which allocation of resources to reproduction jeopardizes somatic repair mechanisms and hence longevity. Selection intensity on early, beneficial effects will be stronger than on later, deleterious ones and so the optimal life history will include aging.

> The optimality account of ageing has come to be known as the `pleiotropy theory of senescence`, because **it is often developed in terms of genes with effects on more than one aspect of the phenotype**, in this case on survival and fertility at different ages. 

[Wensink.et.al.-.2014.-.Interaction.Mortality.Senescence.May.Have.Evolved](https://github.com/jehoons/sbie_aging/files/790601/Wensink.et.al.-.2014.-.Interaction.Mortality.Senescence.May.Have.Evolved.PDF)

**Comment by sugyun** [comment]
Wensink.et.al.-.2014.-.Interaction.Mortality.Senescence.May.Have.Evolved 읽음
내용을 요약하자면, 
(1) 위험 함수에서 환경('E')으로 부터의 위협에 대처하면서 그 trade-off로서 수명을 줄이는 parameter ('k')와 ('k'가 수명에 얼마나 영향을 주는지에 대한) parameter ('s')을
(2) 번식과 생존함수가 포함되어 있는 함수에서 fitness ('r')가 최대가 되도록 최적화하면
(3) 최적의 노화 빠르기가 나오고 그 노화 빠르기는 para에 따라 범위가 넓으며
(4) 환경 영향이 커질수록 노화 빠르기가 빨라지는 경향을 보여준다.
=> 정리하여 말하자면 **노화의 빠르기**라는 것이 환경과 환경에 대처하는 방식 그리고 그러한 방식이 수명에 미치는 영향들에 따라 번식과 생존을 **최적화하도록 fitting**되어 있다는 것이다.
