### ISSUE TITLE
Longevity and Stemcell differentiation - Yamanaka

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#19]
[Sánchez Alvarado 그리고 Yamanaka - 2014 - Rethinking Differentiation Stem Cells, Regenerati.pdf](https://www.dropbox.com/s/xmgym3fbigoh30c/S%C3%A1nchez%20Alvarado%20%EA%B7%B8%EB%A6%AC%EA%B3%A0%20Yamanaka%20-%202014%20-%20Rethinking%20Differentiation%20Stem%20Cells%2C%20Regenerati.pdf?dl=0)

**Comment by sugyun** [comment]
논문에서 한 문장을 건졌습니다. 
=> 분화된 상태, 질병 상태, 노화 상태 모두 하나의 안정적인 attractor이므로 reprogramming가능하다는 내용입니다.
"""
it appears that, in nature, for many cells and in many organisms, the differentiated state is not terminal but is instead stable and that, under varied environmental conditions such as injury and disease or even the natural process of aging, such a state can be reprogrammed.
"""

**Comment by jehoons** [comment]
화이팅

2017. 3. 17. 오후 11:03에 "sugyun" <notifications@github.com>님이 작성:
