### ISSUE TITLE
Simulate the model with different input-condition

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#22]
DNA damage, LowNutEx - 4 cases
- [x] make input conditions 
- [x] simulate 

- [ ] 프로그램 [test_c.py](https://github.com/jehoons/sbie_aging/blob/master/results/table_s1/test_c.py) 수정하기

**Comment by sugyun** [comment]
@jehoons  test_c.py 위치가 깨졌습니다~~

**Comment by jehoons** [comment]
아까 논의했듯이, 프로그램이 다소 업데이트 되었기 때문에 해당 파일은 유효하지 않습니다. 하지만 내용은 test_b.py에서 확인할 수 있을 것입니다.
