### ISSUE TITLE
Check - aging video

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#34]
- [x] [구글 강연](https://youtu.be/tXJzvo0Jekc)
> 수염난 아저씨는 *Aubrey de Grey*라는 사람. Aubrey David Nicholas Jasper de Grey is an English author and biomedical gerontologist, currently the Chief Science Officer of the SENS Research Foundation - from Wiki.

또한 [TED강연, 한글번역](https://www.ted.com/talks/aubrey_de_grey_says_we_can_avoid_aging/transcript?language=ko)를 살펴볼 필요가 있습니다. 
> 우선 저는 노화를 막는 것이 가능한지에 대해 말해보겠습니다. 노화를 방지하는 것이 불가능하다고 많은 사람들이 생각하는 가장 기본적인 이유는 제가 지금 내리는 노화에 대한 정의에서 설명될 수 있습니다. 노화라는 것은 아주 간단하게 정의할 수 있습니다. 노화라는 것은 살아있는 것의 부작용입니다. 즉, 신진대사의 부작용이라는 것이지요. 이것은 완전히 중언부언하는 말은 아닙니다. 충분히 설득력과 근거가 있는 말입니다. 노화는 기본적으로 차와 같은 생명이 없는 물체에 일어나는 과정으로 우리에게도 일어납니다. 우리 몸은 자체 회복 능력이 있음에도 불구하고우리가 노화되는 것은 자체 회복 능력이 완벽하지 않기 때문입니다.

>따라서 기본적으로 신진대사는 우리가 하루하루 살아갈 수 있도록 도와주면서 한편으로는 부작용을 가지고 있는 것이라 정의할 수 있습니다. 그 부작용들은 쌓이고 쌓여서 결국 건강에 이상을 초래합니다. 지금 제가 말씀드린 것이 신진대사에 대한 정의라고 할 수 있습니다. 결국 우리는 이렇게 볼 수 있습니다. 우리는 모든 일에 대해 일련의 과정을 가지고 있습니다. 노화의 진행속도를 느리게하기 위해서는 2가지를 모두 잡아야한다고 사람들은 생각합니다. 저는 오늘 그 2가지를 "노인학적 접근"과 "노인병학적 접근"이라고 부르겠습니다. 노인학 전문의사에 대한 이야기는 조금 있다가 하겠습니다. 병리학에 대한 것을 조금 알고, 노인학 전문의사들이 인간에게 시간이 흐르는 것을 조금 막아보려는 노력을 하며, 병리학을 일으키는 부작용들을 막는다는 이야기를 할 때 말입니다. 물론 제가 말할 것은 단기간에만 효과를 낼 수 있으면서 장기전으로 봤을 때는 승산이 없는 이야기일 수 있습니다. 왜냐하면 노화는 결국 사람들을 병에 걸리게 하고, 병에 걸리는 빈도수는 시간이 흐르면서 점점 커지게 되기 때문입니다.

>우선 저는 왜 이 리스트가 완벽하게 채워졌는지에 대해 말씀드리려 합니다. 물론 누군가는 생물학적으로 접근해서 말할 수도 있겠지만 말이죠. 어떤 사람은 이렇게 말할 수 있습니다. 우리는 무엇으로 만들어졌지요? 우리는 세포와 세포 사이에 있는 물질들로 만들어졌습니다. 어떠한 위험들이 축적되어 있을까요? 정답은 수명이 긴 세포들입니다. 왜냐하면 단수명 세포들은 손상을 입으면 단백질 가수 분해에 의해 단백질이 파괴되듯이 파괴되면서 손상 또한 사라지기 때문입니다. 그렇게 되면 문제는 장수명 세포가 됩니다. 

흥미로운 질문 

> 관객: 지구 상의 종들은 번식을 할 수 있을 때까지 살기 위해 면역체계를 발달 시키며 진화해왔습니다. 하지만 제가 아는 바로는 종들은 죽기 위해서 발전해왔다는 것입니다. 세포들이 분열될 때마다 말단 소립은 더 짧아지고 결국 죽게 되기 때문이지요. 그렇다면 왜 진화는 불멸에 반대되는 방법을 선택했을까요? 아니면 진화는 결점이 있는 과정인 것인가요?

> AG: 좋은 질문이네요. 제가 논쟁의 여지가 없는 대답을 해드릴 수 있겠군요. 제가 말씀드릴 대답은 현재 많은 사람들이 동의하고 있는 것이고 저 또한 동의하는 대답입니다. 노화라는 것은 선택의 결과가 아니고, 진화는 진화에 대한 무관심의 결과라는 것이지요. 다른 말로, 노화가 진행되는 이유는 노화하지 않는 것이 어렵기 때문인 것이지요. 노화되는 속도를 줄이기 위해서는 더 유전학적인 방법과 더 복잡하고 정교한 유전자를 필요로 합니다. 그리고 그 유전자들은 우리가 더 많이 자극할수록 더 오랫동안 존속합니다. 따라서 진화의 정도는 크게 문제가 되지 않습니다. 유전자들이 각각의 형태로 변화하고, 오랜 시간동안 존속해 있거나 생식하고 있는 지에 대해서도 별로 상관이 없습니다. 물론 각각에 대한 조절은 있지만 말이지요. 그 각각의 조절로 인해 다른 종류의 동물들이 서로 다른 수명을 가지고 있는 것이지만, 그것이 결코 죽지 않는 종이 없다는 것과는 관계가 없습니다.
> CA: 그렇다면 유전자는 별로 상관하지 않는 일을 가지고 우리가 신경쓴다는 말인가요?
> AG: 네, 그렇습니다.

- [x] [의식을 로봇에](https://www.youtube.com/watch?v=Nv19Q-v2YWk)

- [x] [현재 진행중인 영생 프로젝트](https://www.youtube.com/watch?v=iPQt2yDezrU)

- [x] [Can we engineer the end of ageing? | Daisy Robinton | TEDxLondonSalon](https://youtu.be/sAChp49XgWA)

**Comment by sugyun** [comment]
수염난 아저씨의 reverse aging approach가 우리와는 다름. 데미지를 주기적으로 적당히 치료해서 발병의 임계값을 넘기지 않는 전략.
"Let's go and periodically repair all of these various types of damage — not necessarily repair them completely, but repair them quite a lot, so that we keep the level of damage down below the threshold that must exist, that causes it to be pathogenic."

**Comment by sugyun** [comment]
Tony Wyss-Coray: How young blood might help reverse aging. Yes, really
- [x]  https://www.ted.com/talks/tony_wyss_coray_how_young_blood_might_help_reverse_aging_yes_really
