### ISSUE TITLE
2차 시도 과제 작성 방향 토론 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#36]
이곳에 금일의 논의 사항을 정리해 주시길 바랍니다. 

[2페이지 계획서](https://drive.google.com/open?id=0B5ZzQIc13NQ9NmJaTVZSZV9Xbms)파일을 읽어보시고, 무엇이 문제인지 비판해 주시고, 가능하다면 개선 방향 또한 생각해서 정리해 주세요.

**Comment by sugyun** [comment]
가제 : 시스템 생물학을 이용한 암화 억제 안티 에이징 메커니즘 연구
- 네트워크 구축 (암 + 에이징 네트워크)
- 암에 대한 시스템 생물학적 논문 있음(연구실)
- 부분적 재분화의 문제점 => 암화
- 메커니즘까지 밝히는 것으로!
=> 기초과학 카테고리

기존 계획서의 새로운 관점 제시 등과 같은 애매한 말 다수 포함

**Comment by soobeom** [comment]
문제점은 너무 많은 추상적 목표들. 
좀 더 구체적인 목표로 noble point를 어필하는 것이 좋을 것이라고 생각함. 
- 암 네트워크와 노화 네트워크의 비교분석을 통해 암과 노화의 correlation을 메커니즘 수준에서 규명
- 이를 위한 integrative, comprehensive network를 구축하는 것 
- 거대한 네트워크를 효과적으로 제어하기 위한 제어전략
- reversion이라는 키워드 부각

**Comment by jehoons** [comment]
수균이 작성: 

방법 : 시스템 생물학 및 제어이론
목표 : 암을 억제하며 노화를 역행
=> 시스템 생물학 및 제어이론을 활용한 암화 배제 역노화 메커니즘 연구
=> 암과 노화를 동시에 억제하는 분자 타겟 발굴을 위한 메커니즘 연구
