### ISSUE TITLE
수균이 - 모델비교, MSigDB활용, 네가티브피드백 제거하고 테스트하기 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#38]
- [x] PLOS One 페이퍼 geroconversion 모델과 우리의 모델을 상호비교 분석 
- [ ] MSigDB활용, 어트렉터 해석하기 
- [x] Negative feedback을 제외하고 계산해보기

**Comment by sugyun** [comment]
- PLOS One 페이퍼의 FP
Insulin -- GF -- p21 -- mTORC1_S6K1 -- Senescence -- Metabolism -- MAPK -- p53 -- IRS_PIK3CA -- PTEN -- ATP -- RB1 -- PP1C
<=> 
input_condition: {'IGF1': True, 'LowNuEx': False, 'DNAdamage': True}
type cyclic ratio 0.3208
sign,AKT,AMPK,ATG13,ATG5,ATP,AXP,BAX,BIM,BMI1,Bcl2,CDK,DNAdamage,E2F,ERK,FOUR_EBP1,FOXO,G6pase,GLUT4,Glucose,Glycolysis,IGF1,IGF1R,IRS,LC,LowNuEx,MDM2,MKK,MnSOD,NAD,PDK,PGC1a,PI3K,PTEN,RAS,RB1,ROS,Rheb,S6K,SGK,SIRT1,TCAcyc,TSC,ULK1,caspase3,mTOR,p16,p21,p27,p38MAPK,p53
c24ce93be3,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1,0,0,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0,1,0,0,1,0,1,0,0,1,0
a99781f3dc,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,1,1,0,0,1,1,0,1,0,1,1,0,0,1,1
5f635358ef,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,1,0,0,1,0,0,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,0,1,0
f8a55f3d9a,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,1,1,0,0,0,0,1,0,1,0,0,0,0,1,1,0,1,1,1,0,1,0,0,1,0,1,0,0,1,1
a24c00912b,0,1,1,0,1,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,1,0,1,0,1,1,0,0,1,1
44e13d6754,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0
f6cac6fb66,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,0,0,1,1
7a63d31213,0,1,1,0,1,0,1,0,0,0,0,1,0,1,1,0,0,0,1,1,1,1,1,0,0,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,0,1,0,1,1,1,0,1,0

type cyclic ratio 0.6792
sign,AKT,AMPK,ATG13,ATG5,ATP,AXP,BAX,BIM,BMI1,Bcl2,CDK,DNAdamage,E2F,ERK,FOUR_EBP1,FOXO,G6pase,GLUT4,Glucose,Glycolysis,IGF1,IGF1R,IRS,LC,LowNuEx,MDM2,MKK,MnSOD,NAD,PDK,PGC1a,PI3K,PTEN,RAS,RB1,ROS,Rheb,S6K,SGK,SIRT1,TCAcyc,TSC,ULK1,caspase3,mTOR,p16,p21,p27,p38MAPK,p53
c9fa39a647,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,1,0,0,1,0,1,0,1,1,1,1,1,0,0,1,0,0,0,1,1,0,0,1,0
ece50f91bb,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,1,0,1,0,1,1,1,1,1,1,0,1,0,0,0,1,1,0,0,1,1
f6a1d7a55e,1,1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,1,1,1,1,1,1,1,0,1,0,0,0,1,1,0,0,1,1
330086d9f8,1,1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1
55276e0fd1,0,1,1,0,0,0,0,0,1,0,1,1,0,1,1,0,0,1,1,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,1,1
83330d1f74,0,1,1,0,0,0,1,0,0,0,1,1,0,1,1,0,0,1,1,1,1,1,1,0,0,0,1,0,1,0,1,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,1,0,1,0
45cb2579b4,0,0,1,0,1,0,0,0,0,0,0,1,1,1,1,0,0,1,1,1,1,1,1,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1,1,0,0,1,0,1,0,0,1,0
69f68b2b4c,0,0,1,0,1,0,0,0,0,0,0,1,1,1,1,0,0,1,1,1,1,1,1,0,0,0,1,0,0,0,0,1,0,1,1,1,1,0,0,1,1,0,1,0,1,1,0,0,1,0
