### ISSUE TITLE
2차 과제 제안서

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#39]
- [ ] 제목?

**Comment by sugyun** [comment]
방법 : 시스템 생물학 및 제어이론
목표 : 암을 억제하며 노화를 역행
=> 시스템 생물학 및 제어이론을 활용한 암화 배제 역노화 메커니즘 연구
=> 암과 노화를 동시에 억제하는 분자 타겟 발굴을 위한 메커니즘 연구

**Comment by jehoons** [comment]
#36 으로 통합
