### ISSUE TITLE
Human ageing genomic resources (HAGR, meta-database) 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#4]
[paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3531213/pdf/gks1155.pdf)에서 노화표현형을 어떻게 정의하였고 무엇을 노화에 의한 변화로 생각하는지를 살펴볼 필요가 있다. HAGR 응용사례 또한 언급되어있음.

좋아 보임

- [x] 논문읽기
- [x] 관련응용사례 살펴보기
- [ ] 데이터베이스테스트
- [ ] 응용방안 생각해보기

**Comment by urkang** [comment]
Step #1. 논문 내용정리

* Abstract
- Human Ageing Genomic Resources(HAGR)
  : 다양한 생명체의 노화현상과 관련된 genomic database, research tool들을 모아둔 meta-database
- 2004년에 launching, 1st data release
- 2013년 1월 현재, 크게 3가지 database가 존재
 (1) GenAge : genomic database, human과 model organism들의 ageing-related gene을 정리함
 (2) AnAge : non-genomic database, 4000종 이상 동물들의 장수에 관련된 기록, 표현형 특징 등을 정리함
 (3) GenDR : Dietary-restriction(DR) related gene을 정리함
- 노화관련 연구분야에서는 가장 신뢰받는 데이터베이스로 자리잡음
- 본 논문에서는 3가지 주요 데이터베이스의 발전상과, 주요 업데이트 사항에 대해 설명하였음

**Comment by urkang** [comment]
Step #2. HAGR에서 파생된 응용사례들 조사

**Comment by urkang** [comment]
* HAGR is also highlighted in 
- Science (307:187)
- Nature Reviews Genetics (5:1362)
- BioTechniques (39:21)

* HAGR's scientific strategies in
- http://genomics.senescence.info/science.html

**Comment by urkang** [comment]
본 논문이 인용하고 있는, 34개의 reference들을 간략하게 살펴보는것도 도움이 될 것으로 생각합니다.

**Comment by urkang** [comment]
[Scientific strategy of HAGR.pdf](https://github.com/jehoons/sbie_aging/files/775547/Scientific.strategy.of.HAGR.pdf)

**Comment by jehoons** [comment]
최근의 동향을 보면 노화가 진화의 산물이거나 부산물로써 보고, 비교생물학적 방법을 통해서 노화와 관련한 생체의 하위구조(또는
메커니즘)을 식별하려는 것 같구나.

**Comment by jehoons** [comment]
최근의 동향을 보면 노화가 진화의 산물이거나 부산물로써 보고, 비교생물학적 방법을 통해서 노화와 관련한 생체의 하위구조(또는 메커니즘)을 식별하려는 것 같구나.
