### ISSUE TITLE
Meeting 5/2, 모델링을 위한 데이터수집

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#47]
### 1. 데이터 수집하기 
노화와 암에 관한 세포주 수준의 실험논문을 리뷰하고, 논문 내의 실험 데이터를 수집 후 어떤 세포주를 중심으로 모델을 fine-tuning할지를 결정하기로 하자.

데이터를 수집할때에는 다음 사항이 포함되게 한다: 
* 실험생물
* 방법
* Treatment (처리약물) - Observation (분자측정, 페노타입 관찰)
예를 들면, (treatment: Rapamycin,...) and (observation: mTOR,S6K,...) 

참고사항 
https://www.ncbi.nlm.nih.gov/pubmed/21084729
[Common biology of cancer](https://www.dropbox.com/s/rvifewo2l6lkxew/Finkel%20et%20al.%20-%202007%20-%20The%20common%20biology%20of%20cancer%20and%20ageing.pdf?dl=1) - 이 논문을 인용한 논문들을 살펴보면 좋을 듯. 

### 2. 머신러닝 논문 리뷰하기 
[감독관 학습방법에 관한 리뷰논문](https://www.ncbi.nlm.nih.gov/pubmed/28265788)

**Comment by jehoons** [comment]
토론할 꺼리들: 
노화가 암을 억제하려는 인체의 노력일까? 
https://www.quora.com/Is-aging-a-bodys-attempt-to-prevent-cancer

**Comment by sugyun** [comment]
실험생물 : female outbred SHR mice
방법 : metformin treatment (100 mg/kg in drinking water)
Treatment : metformin
Observation (페노타입)
switch-off of estrous(발정) function, increased mean life span by 37.8%
failed influence blood estradiol concentration and spontaneous tumor incidence
[Metformin slows down aging and extends life span of female SHR mice](http://www.tandfonline.com/doi/abs/10.4161/cc.7.17.6625#aHR0cDovL3d3dy50YW5kZm9ubGluZS5jb20vZG9pL3BkZi8xMC40MTYxL2NjLjcuMTcuNjYyNT9uZWVkQWNjZXNzPXRydWVAQEAw)

**Comment by sugyun** [comment]
이 논문도 같이 살펴보면 좋을 것 같습니다.
[Metformin – its potential anti-cancer and anti-aging effects](https://github.com/jehoons/sbie_aging/files/964532/fulltext516.pdf)
![image](https://cloud.githubusercontent.com/assets/22545969/25532074/ea9e2030-2c66-11e7-9d7a-9db115cc8c24.png)
