### ISSUE TITLE
논문데이터  정량화하기 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#52]
웨스턴블럿 정량화 
https://www.youtube.com/watch?v=MINYgJeSKGY

논문 데이터 정량화 
[Engauge.zip](https://github.com/jehoons/sbie_aging/files/972368/Engauge.zip)

![image](https://cloud.githubusercontent.com/assets/10771513/25646738/3150d616-2ff6-11e7-81a7-b1c2ae40e1fb.png)

**Comment by sugyun** [comment]
fibroblast의 perturbation에 대한 데이터 모으기 (aging 및 normal)
