### ISSUE TITLE
생로병사의 비밀

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#54]
https://www.dropbox.com/s/wr1r4rs5s24llde/170503.%EC%83%9D%EB%A1%9C%EB%B3%91%EC%82%AC%EC%9D%98%20%EB%B9%84%EB%B0%80%20%E3%80%8C%EB%AA%B8%EC%9D%B4%20%EC%A0%8A%EC%96%B4%EC%A7%80%EB%8A%94%20%EA%B8%B0%EC%88%A0%2C%20%EC%95%88%ED%8B%B0%EC%97%90%EC%9D%B4%EC%A7%95%E3%80%8D.H264.AAC.720p-CineBus.mp4?dl=0

**Comment by urkang** [comment]
링크 변경 >>
https://www.dropbox.com/s/2n2hanf9guk5v03/170503.%EC%83%9D%EB%A1%9C%EB%B3%91%EC%82%AC%EC%9D%98%20%EB%B9%84%EB%B0%80%20%E3%80%8C%EB%AA%B8%EC%9D%B4%20%EC%A0%8A%EC%96%B4%EC%A7%80%EB%8A%94%20%EA%B8%B0%EC%88%A0%2C%20%EC%95%88%ED%8B%B0%EC%97%90%EC%9D%B4%EC%A7%95%E3%80%8D.H264.AAC.720p-CineBus.mp4?dl=0
