### ISSUE TITLE
5/23 미팅

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#62]
- [x] 수범이 실험관련 자료 
- [x] 수균이 pertbio 논문 
- [x] 의룡이 fibroblast 연령변화에 따른 seq데이터 찾아보기 
- [x] 연구계획서 관련 작업

**Comment by urkang** [comment]
연령대별 fibroblast sequencing 데이터의 주요 탐색 결과는 아래와 같았습니다.

Saini, Natalie, et al. "The Impact of Environmental and Endogenous Damage on Somatic Mutation Load in Human Skin Fibroblasts." PLoS Genet 12.10 (2016): e1006385.
>> Accumulation of somatic changes, due to environmental and endogenous lesions, in the human genome is associated with aging and cancer. Understanding the impacts of these processes on mutagenesis is fundamental to understanding the etiology, and improving the prognosis and prevention of cancers and other genetic diseases. Previous methods relying on either the generation of induced pluripotent stem cells, or sequencing of single-cell genomes were inherently error-prone and did not allow independent validation of the mutations. In the current study we eliminated these potential sources of error by high coverage genome sequencing of single-cell derived clonal fibroblast lineages, obtained after minimal propagation in culture, prepared from skin biopsies of two healthy adult humans. We report here accurate measurement of genome-wide magnitude and spectra of mutations accrued in skin fibroblasts of healthy adult humans. We found that every cell contains at least one chromosomal rearrangement and 600–13,000 base substitutions. The spectra and correlation of base substitutions with epigenomic features resemble many cancers. Moreover, because biopsies were taken from body parts differing by sun exposure, we can delineate the precise contributions of environmental and endogenous factors to the accrual of genetic changes within the same individual. We show here that UV-induced and endogenous DNA damage can have a comparable impact on the somatic mutation loads in skin fibroblasts.

Abyzov, Alexej, et al. "One thousand somatic SNVs per skin fibroblast cell set baseline of mosaic mutational load with patterns that suggest proliferative origin." Genome Research 27.4 (2017): 512-523.
>> Few studies have been conducted to understand post-zygotic accumulation of mutations in cells of the healthy human body. We reprogrammed 32 skin fibroblast cells from families of donors into human induced pluripotent stem cell (hiPSC) lines. The clonal nature of hiPSC lines allows a high-resolution analysis of the genomes of the founder fibroblast cells without being confounded by the artifacts of single-cell whole-genome amplification. We estimate that on average a fibroblast cell in children has 1035 mostly benign mosaic SNVs. On average, 235 SNVs could be directly confirmed in the original fibroblast population by ultradeep sequencing, down to an allele frequency (AF) of 0.1%. More sensitive droplet digital PCR experiments confirmed more SNVs as mosaic with AF as low as 0.01%, suggesting that 1035 mosaic SNVs per fibroblast cell is the true average. Similar analyses in adults revealed no significant increase in the number of SNVs per cell, suggesting that a major fraction of mosaic SNVs in fibroblasts arises during development. Mosaic SNVs were distributed uniformly across the genome and were enriched in a mutational signature previously observed in cancers and in de novo variants and which, we hypothesize, is a hallmark of normal cell proliferation. Finally, AF distribution of mosaic SNVs had distinct narrow peaks, which could be a characteristic of clonal cell selection, clonal expansion, or both. These findings reveal a large degree of somatic mosaicism in healthy human tissues, link de novo and cancer mutations to somatic mosaicism, and couple somatic mosaicism with cell proliferation.

**Comment by urkang** [comment]
- Data availability 관련사항 추가합니다.

**Saini, Natalie, et al. "The Impact of Environmental and Endogenous Damage on Somatic Mutation Load in Human Skin Fibroblasts." PLoS Genet 12.10 (2016): e1006385.**
Data Availability: The final BAM files and complete lists of somatic mutation calls in whole genome sequenced and whole exome sequenced samples have been deposited into dbGAP approved study under accession number phs001182.v1.p1. The URL for accessing the study in dbGAP is http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001182.v1.p1.
