### ISSUE TITLE
논문 제본 리스트 

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#72]
이 연구와 밀접한 관련이 있는 **핵심논문 20**개를 선정해서 제본하고자 합니다. 좋은 것이 있으면 여기에 추천해 주기 바랍니다 

1. Campisi, J. (2013). Aging, Cellular Senescence, and Cancer. Annual Review of Physiology 75, 685–705.

**Comment by sugyun** [comment]
1. 에이징 및 노화세포 리뷰
[Riera et al. - 2016 - Signaling Networks Determining Life Span.pdf](https://github.com/jehoons/sbie_aging/files/1263498/Riera.et.al.-.2016.-.Signaling.Networks.Determining.Life.Span.pdf)
[van Deursen - 2014 - The role of senescent cells in ageing.pdf](https://github.com/jehoons/sbie_aging/files/1263499/van.Deursen.-.2014.-.The.role.of.senescent.cells.in.ageing.pdf)
[annurev-physiol-030212-183653.pdf](https://github.com/jehoons/sbie_aging/files/1263500/annurev-physiol-030212-183653.pdf)

2. 노화 이론
[Rodríguez et al. - 2017 - Antagonistic pleiotropy and mutation accumulation influence human senescence and disease.pdf](https://github.com/jehoons/sbie_aging/files/1263502/Rodriguez.et.al.-.2017.-.Antagonistic.pleiotropy.and.mutation.accumulation.influence.human.senescence.and.disease.pdf)
[Aging is not programmed.pdf](https://github.com/jehoons/sbie_aging/files/1263506/Aging.is.not.programmed.pdf)

3. SASP
[annurev-pathol-121808-102144.pdf](https://github.com/jehoons/sbie_aging/files/1263519/annurev-pathol-121808-102144.pdf)
[11357_2016_Article_9886 (3).pdf](https://github.com/jehoons/sbie_aging/files/1263520/11357_2016_Article_9886.3.pdf)

4. 노화 치료
[Jeon et al 2017.pdf](https://github.com/jehoons/sbie_aging/files/1263523/Jeon.et.al.2017.pdf)


5. 네트워크 연구
[Zhao 그리고 Wang - 2016 - Uncovering the mechanisms of iCaenorhabditis ele.pdf](https://github.com/jehoons/sbie_aging/files/1263526/Zhao.Wang.-.2016.-.Uncovering.the.mechanisms.of.iCaenorhabditis.ele.pdf)
[Verlingue et al. - 2016 - A comprehensive approach to the molecular determinants of lifespan using a Boolean model of geroconversion.pdf](https://github.com/jehoons/sbie_aging/files/1263527/Verlingue.et.al.-.2016.-.A.comprehensive.approach.to.the.molecular.determinants.of.lifespan.using.a.Boolean.model.of.geroconversion.pdf)

**Comment by sugyun** [comment]
6.  CNO
[CNO.pdf](https://github.com/jehoons/sbie_aging/files/1279529/CNO.pdf)
[DrugResistanceMechanismsinColorectalCancer.pdf](https://github.com/jehoons/sbie_aging/files/1279530/DrugResistanceMechanismsinColorectalCancer.pdf)

**Comment by sugyun** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2873544/pdf/1471-2105-11-233.pdf
