### ISSUE TITLE
RPPA Feature Selection by 제훈

### ISSUE THREAD

**Issue by jehoons** [jehoons/sbie_aging#98]
[aging-team-170830 - short.pptx](https://github.com/jehoons/sbie_aging/files/1260262/aging-team-170830.-.short.pptx)

[aging-team-170830.-.short-rev1.pptx](https://github.com/jehoons/sbie_aging/files/1269510/aging-team-170830.-.short-rev1.pptx)

**Comment by sugyun** [comment]
list_sg = ['FKBP4','BLNK','DDX5','CCND1','MAPK14','FLT3','PLCG1','ELK1','RPS6KA5','ITGB3','ICK','STAT3','BCL2A1','TP53','AKT1','FCGR2A','CALM2','ASRGL1','IL7R','ATRIP','A2M','PTK2B','LIMK1','EIF4EBP1','CDH5','NF2','PLCG2','PEA15','PCMT1','RGS16','IKBKG','GLMN','CHUK','ABL1','HDAC1','SNRPE','LYN','RPS6KA1','APAF1']

list_jh =
['fcgr2a', 'map2k1', 'tank', 'ptk2b', 'jund', 'met','cxcr4', 'hdac1', 'eif4ebp1', 'gsk3a', 'ppp2r4','slc6a13','casp9', 'elk1', 'ankrd23', 'hnf4a', 'myc']

**intersection = ['ELK1', 'FCGR2A', 'HDAC1', 'PTK2B', 'EIF4EBP1']**

**Comment by jehoons** [comment]
클러스터링 결과 (고해상도 이미지)  
![figure-clustermap-cutoff 0 8](https://user-images.githubusercontent.com/10771513/29996959-4120d6b0-9043-11e7-9231-5a8ba7b0d5c9.png)

**Comment by jehoons** [comment]
클러스터링 그림 및 antibody's full name 
[chk-clustermap.zip](https://github.com/jehoons/sbie_aging/files/1272791/chk-clustermap.zip)

**Comment by jehoons** [comment]
[chk-feature-sel.zip](https://github.com/jehoons/sbie_aging/files/1277512/chk-feature-sel.zip)

```
{
    "cutoff=0.20": {
        "intersection": [
            "14-3-3 zeta/delta (Ab-232)",
            "HDAC1 (Ab-421)",
            "VEGFR2 (Ab-951)",
            "4E-BP1 (Ab-65)",
            "ACC1 (Phospho-Ser80)",
            "Abl1 (Ab-204)",
            "VE-Cadherin (Phospho-Tyr731)",
            "DAXX (Phospho-Ser668)",
            "CD32 (FcgammaRIIb)(Ab-292)",
            "Shc (Ab-427)",
            "IKK-alpha/beta (Phospho-Ser180/181)",
            "ETK (Ab-40)",
            "BRCA1 (Phospho-Ser1423)",
            "ATF2 (Ab-69/51)",
            "Abl1 (Ab-754/735)",
            "Caspase 9 (Ab-153)",
            "MEK1 (Phospho-Thr286)",
            "MSK1 (Phospho-Ser212)",
            "P90RSK (Ab-573)",
            "CBL (Phospho-Tyr700)",
            "MEK2 (Phospho-Thr394)",
            "Elk1 (Phospho-Ser383)",
            "P90RSK (Phospho-Thr359/Ser363)",
            "NFkB-p100/p52 (Phospho-Ser872)",
            "Pyk2 (Ab-881)",
            "PLCG1 (Ab-771)"
        ],
        "num_intersection": 26,
        "IGF": [
            "c-Jun (Phospho-Ser63)",
            "GSK3 beta (Phospho-Ser9)",
            "c-Jun (Phospho-Ser73)",
            "Elk1 (Phospho-Ser383)",
            "PDK1 (Phospho-Ser241)",
            "GSK3 alpha (Phospho-Ser21)",
            "MEK2 (Phospho-Thr394)",
            "NFkB-p65 (Phospho-Ser468)",
            "NFkB-p65 (Phospho-Ser536)",
            "NFkB-p100/p52 (Phospho-Ser865)",
            "MKK4/SEK1 (Phospho-Ser80)",
...
```

**Comment by jehoons** [comment]
### Early, Late로 구분하여 Feature Selection 한것
[chk-test_avgstd-feature-sel.zip](https://github.com/jehoons/sbie_aging/files/1283503/chk-test_avgstd-feature-sel.zip)

**Comment by sugyun** [comment]
[170910_FEATUREGENESYM.xlsx](https://github.com/jehoons/sbie_aging/files/1290457/170910_FEATUREGENESYM.xlsx)

**Comment by jehoons** [comment]
피처선택하기 - 설명자료 
[aging-team-170920 - short.pptx](https://github.com/jehoons/sbie_aging/files/1332101/aging-team-170920.-.short.pptx)
